// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bqvgdjbienyflozzbmaj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJxdmdkamJpZW55ZmxvenpibWFqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUwMzg4OTAsImV4cCI6MjA2MDYxNDg5MH0.KQnj5i2HpNeNF1Zl0E1RchLQcMV-tru1AY5CwHck1_c";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);